displayName=Customize a Lot
author=Ruined Heir
description=Customize hitsplats, health bars, overhead chat, and head icons for players and NPCs.
tags=hitsplat,hitsplats,hit,splat,damage,heal,healing,combat,customize,layout,filter,healthbar,chat,prayer,skull,overhead,icon
version=
plugins=com.customizealot.CustomizeALotPlugin
build=standard
